/**
 * Convert a camelCase or PascalCase string to snake_case.
 */
export function toSnakeCase(str: string): string {
  return str
    .replace(/([A-Z])/g, '_$1')
    .toLowerCase()
    .replace(/^_/, '');
}

/**
 * Convert a PascalCase model name to a snake_case file name.
 */
export function modelToFileName(modelName: string): string {
  return toSnakeCase(modelName);
}

/**
 * Generate a Python file header comment.
 */
export function fileHeader(): string {
  return [
    '# This file was generated by prisma-python-generator.',
    '# Do not edit manually.',
    '',
  ].join('\n');
}
